// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJW7z-9j7rpfDd50ZdyBjPe2xpD4FJtIc',
    appId: '1:396443077945:web:cbbdfeb3983cb3dbeaace8',
    messagingSenderId: '396443077945',
    projectId: 'mandeep-driver',
    authDomain: 'mandeep-driver.firebaseapp.com',
    storageBucket: 'mandeep-driver.firebasestorage.app',
    measurementId: 'G-X59NVWHTB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3qSjA4Z6bhS-VMsHQsleHP72-PetcgTk',
    appId: '1:396443077945:android:efe0166f5bdff330eaace8',
    messagingSenderId: '396443077945',
    projectId: 'mandeep-driver',
    storageBucket: 'mandeep-driver.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDELQ-FJ5htzPm4yx2bMZm6dsGEK9P7ux0',
    appId: '1:396443077945:ios:5b2b085a543ec94feaace8',
    messagingSenderId: '396443077945',
    projectId: 'mandeep-driver',
    storageBucket: 'mandeep-driver.firebasestorage.app',
    iosBundleId: 'com.elate.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDELQ-FJ5htzPm4yx2bMZm6dsGEK9P7ux0',
    appId: '1:396443077945:ios:5b2b085a543ec94feaace8',
    messagingSenderId: '396443077945',
    projectId: 'mandeep-driver',
    storageBucket: 'mandeep-driver.firebasestorage.app',
    iosBundleId: 'com.elate.driver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJW7z-9j7rpfDd50ZdyBjPe2xpD4FJtIc',
    appId: '1:396443077945:web:eb6b3541d5542c22eaace8',
    messagingSenderId: '396443077945',
    projectId: 'mandeep-driver',
    authDomain: 'mandeep-driver.firebaseapp.com',
    storageBucket: 'mandeep-driver.firebasestorage.app',
    measurementId: 'G-8GTYLCDK1B',
  );
}
